# cm_config.ini 示例配置文件

# 门的角度配置
angle_open=4.0
angle_close=4.0
angle_max=36.0

# 门打开超时配置
door_open_timeout=300

door_stable_diff=0.1
door_direction=2
angle_capture=30.0
fab_idle_diff=0.1
Filter_Angle=1.0
calib_time=20
